restaurant-service:
  build: ./restaurant-service
  ports:
    - "5001:5001"
  depends_on:
    - mongo
  env_file:
    - ./restaurant-service/.env  # ✅ mora kazati na pravilno lokacijo
  networks:
    - smartnet
