# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import restaurant_pb2 as restaurant__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in restaurant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RestaurantServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddRestaurant = channel.unary_unary(
                '/restaurant.RestaurantService/AddRestaurant',
                request_serializer=restaurant__pb2.AddRestaurantRequest.SerializeToString,
                response_deserializer=restaurant__pb2.AddRestaurantResponse.FromString,
                _registered_method=True)
        self.GetRestaurant = channel.unary_unary(
                '/restaurant.RestaurantService/GetRestaurant',
                request_serializer=restaurant__pb2.GetRestaurantRequest.SerializeToString,
                response_deserializer=restaurant__pb2.GetRestaurantResponse.FromString,
                _registered_method=True)
        self.AddMenu = channel.unary_unary(
                '/restaurant.RestaurantService/AddMenu',
                request_serializer=restaurant__pb2.AddMenuRequest.SerializeToString,
                response_deserializer=restaurant__pb2.AddMenuResponse.FromString,
                _registered_method=True)
        self.GetMenu = channel.unary_unary(
                '/restaurant.RestaurantService/GetMenu',
                request_serializer=restaurant__pb2.GetMenuRequest.SerializeToString,
                response_deserializer=restaurant__pb2.GetMenuResponse.FromString,
                _registered_method=True)
        self.UpdateMenu = channel.unary_unary(
                '/restaurant.RestaurantService/UpdateMenu',
                request_serializer=restaurant__pb2.UpdateMenuRequest.SerializeToString,
                response_deserializer=restaurant__pb2.UpdateMenuResponse.FromString,
                _registered_method=True)
        self.DeleteMenu = channel.unary_unary(
                '/restaurant.RestaurantService/DeleteMenu',
                request_serializer=restaurant__pb2.DeleteMenuRequest.SerializeToString,
                response_deserializer=restaurant__pb2.DeleteMenuResponse.FromString,
                _registered_method=True)


class RestaurantServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddRestaurant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRestaurant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMenu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMenu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMenu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMenu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestaurantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddRestaurant': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRestaurant,
                    request_deserializer=restaurant__pb2.AddRestaurantRequest.FromString,
                    response_serializer=restaurant__pb2.AddRestaurantResponse.SerializeToString,
            ),
            'GetRestaurant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRestaurant,
                    request_deserializer=restaurant__pb2.GetRestaurantRequest.FromString,
                    response_serializer=restaurant__pb2.GetRestaurantResponse.SerializeToString,
            ),
            'AddMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMenu,
                    request_deserializer=restaurant__pb2.AddMenuRequest.FromString,
                    response_serializer=restaurant__pb2.AddMenuResponse.SerializeToString,
            ),
            'GetMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMenu,
                    request_deserializer=restaurant__pb2.GetMenuRequest.FromString,
                    response_serializer=restaurant__pb2.GetMenuResponse.SerializeToString,
            ),
            'UpdateMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMenu,
                    request_deserializer=restaurant__pb2.UpdateMenuRequest.FromString,
                    response_serializer=restaurant__pb2.UpdateMenuResponse.SerializeToString,
            ),
            'DeleteMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMenu,
                    request_deserializer=restaurant__pb2.DeleteMenuRequest.FromString,
                    response_serializer=restaurant__pb2.DeleteMenuResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'restaurant.RestaurantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('restaurant.RestaurantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RestaurantService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddRestaurant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/AddRestaurant',
            restaurant__pb2.AddRestaurantRequest.SerializeToString,
            restaurant__pb2.AddRestaurantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRestaurant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/GetRestaurant',
            restaurant__pb2.GetRestaurantRequest.SerializeToString,
            restaurant__pb2.GetRestaurantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/AddMenu',
            restaurant__pb2.AddMenuRequest.SerializeToString,
            restaurant__pb2.AddMenuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/GetMenu',
            restaurant__pb2.GetMenuRequest.SerializeToString,
            restaurant__pb2.GetMenuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/UpdateMenu',
            restaurant__pb2.UpdateMenuRequest.SerializeToString,
            restaurant__pb2.UpdateMenuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/DeleteMenu',
            restaurant__pb2.DeleteMenuRequest.SerializeToString,
            restaurant__pb2.DeleteMenuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
