name: Test User Service

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📂 Move to correct directory
        run: cd user-service

      - name: 📥 Install dependencies
        run: npm install
        working-directory: user-service

      - name: 🧪 Run Unit Tests
        run: npm test
        working-directory: user-service
