name: Build & Publish Docker Images

# Sproži ob vsakem pushu v branch main
on:
  push:
    branches: [ main ]

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    # Matrix seznam vseh projektov, ki imajo svoj Dockerfile
    strategy:
      matrix:
        service: [
          "user-service",
          "restaurant-service",
          "order-service",
          "web-gateway",
          "mobile-gateway",
          "shell",
          "user-mf",
          "restaurant-mf",
          "order-mf"
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: foolzz/itarhitekture:${{ matrix.service }}:latest
